### ISSUE TITLE
Test for valid sessions once user logins using Events360

### ISSUE THREAD

**Issue by rakesh-pothineni** [CSCE-606-Event360/EventNXT#30]

**Comment by pkavu-1998-tamu** [comment]
In this user story we have tested if sign and sign out for a particular user is working as expected. We have signed in using events360 into eventnxt and then we signed out of eventnxt and tried to sign in again using sign in with evenets360 button. Now user needs to again login since he signed out earlier without directly logging in to eventnxt page.
